name: Mvel PR

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  mvel-build:
    concurrency:
      group: pr-mvel_${{ matrix.os }}_${{ matrix.java-version }}_${{ matrix.maven-version }}_${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 120
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: [8, 11]
        maven-version: ['3.8.7']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / Java-${{ matrix.java-version }} / Maven-${{ matrix.maven-version }}
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Java and Maven Setup
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          maven-version: ${{ matrix.maven-version }}

      - name: Build with Maven
        run: mvn -B clean verify
